# Generated by Django 4.1.7 on 2023-03-11 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAccount',
            fields=[
                ('username', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=2000)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('customer_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=2000)),
                ('middle_name', models.CharField(max_length=2000)),
                ('last_name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('VAT_Number', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp.product')),
                ('name', models.CharField(max_length=1000)),
            ],
            bases=('erp.product',),
        ),
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp.product')),
                ('name', models.CharField(max_length=1000)),
            ],
            bases=('erp.product',),
        ),
        migrations.CreateModel(
            name='InvoiceOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=200)),
                ('products', models.ManyToManyField(to='erp.invoiceoutbound')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=200)),
                ('products', models.ManyToManyField(to='erp.invoiceinbound')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=200)),
                ('products', models.ManyToManyField(to='erp.fiscalnote')),
            ],
        ),
    ]
